EManagement_.UI/Controllers/EmployeeLeaveTypesController.cs
using EManagement_BusinessEngine.Contracts;
using EManagement_Common.ConstantsModels;
using EManagement_Common.VModels;
using EManagement_Data.Contracts;
using EManagement_Data.DbModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EManagement_.Controllers
{
	[Authorize(Roles = ResultConstants.Admin_Role)]
	public class EmployeeLeaveTypesController : Controller
    {
        private readonly IEmployeeLeaveTypeBusinessEngine _employeeLeaveTypeBusinessEngine;
        public EmployeeLeaveTypesController(IEmployeeLeaveTypeBusinessEngine employeeLeaveTypeBusinessEngine)
        {
            _employeeLeaveTypeBusinessEngine = employeeLeaveTypeBusinessEngine;
        }

        
        public IActionResult Index()
        {
            var data = _employeeLeaveTypeBusinessEngine.GetAllEmployeeLeaveTypes();

            if(data.IsSuccess)
            {
                var result = data.Data;
                return View(result);
            }

            return View();
        }

		public IActionResult Create()
		{
			return View();
		}

        [HttpPost]
        public ActionResult Create(EmployeeLeaveTypeViewModel model)
        {
            if(ModelState.IsValid)
            {
                var data = _employeeLeaveTypeBusinessEngine.CreateEmployeeLeaveType(model);
                if(data.IsSuccess)
                {
					return RedirectToAction("Index");
				}return View(model);
            }
            else
            return View(model);
        }

        [HttpGet]
		public ActionResult Edit(int id)
		{
            if(id<0)
            {
                return View();
            }
            var data = _employeeLeaveTypeBusinessEngine.GetAllEmployeeLeaveType(id);
            if(data.IsSuccess)
				return View(data.Data);
			return View();
        }


        [ValidateAntiForgeryToken] //Post operation can not be made without making the get operation
        [HttpPost]
        public ActionResult Edit(EmployeeLeaveTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var data = _employeeLeaveTypeBusinessEngine.EditEmployeeLeaveType(model);
                if (data.IsSuccess)
                {
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            else
                return View(model);
        }


        [HttpDelete]
        public IActionResult Delete(int id)
        {
            if (id <= 0)
                return Json(new { success = false, message = "Select a record to delete." });
            
            var data=_employeeLeaveTypeBusinessEngine.RemoveEmployeeLeaveType(id);
            if(data.IsSuccess)
                return Json(new { success = data.IsSuccess, message = data.Message });
            else
                return Json(new { success = data.IsSuccess, message = data.Message });
        }
    }
}

EManagement_.UI/Views/EmployeeLeaveTypes/Create.cshtml
@model EManagement_Common.VModels.EmployeeLeaveTypeViewModel 

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<form class="form-horizontal" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right" asp-for="Name">Leave Type</label>

        <div class="col-sm-9">
            <input asp-for="Name" type="text" id="form-field-1" placeholder="Leave Type" class="col-xs-10 col-sm-5" />
            <span asp-validation-for="Name"></span>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right" asp-for="DefaultDays">Default Days</label>

        <div class="col-sm-9">
            <input asp-for="DefaultDays" type="number" min="0" max="30" id="form-field-1" placeholder="Default Days" class="col-xs-10 col-sm-5" />
            <span asp-validation-for="DefaultDays"></span>
        </div>
    </div>
    
    <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            @*<button class="btn btn-info" type="button">
            <i class="ace-icon fa fa-check bigger-110"></i>
            Submit
            </button>*@
            <input type="submit" value="Create" class="btn btn-info col-xs-3" />
        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

EManagement_.UI/Views/EmployeeLeaveTypes/Edit.cshtml
@model EManagement_Common.VModels.EmployeeLeaveTypeViewModel

@{
    ViewData["Title"] = "Employee Leave Type Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<form class="form-horizontal" asp-action="Edit">
    @*@Html.HiddenFor(x=>Model.id) alttaki input ifadesiyle aynı anlamda*@
    <input type="hidden" asp-for="id"/>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right" asp-for="Name">Leave Type</label>

        <div class="col-sm-9">
            <input asp-for="Name" type="text" id="form-field-1" placeholder="Leave Type" class="col-xs-10 col-sm-5" />
            <span asp-validation-for="Name"></span>
        </div>
    </div>

    <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
           
            <input type="submit" value="Edit" class="btn btn-info col-xs-3" />
        </div>
    </div>
</form>

EManagement_.UI/Views/EmployeeLeaveTypes/Index.cshtml
@model IEnumerable<EManagement_Common.VModels.EmployeeLeaveTypeViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}



<div class="page-header">
    <h3>
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Employee Leave Types List
        </small>
    </h3>
</div><!-- /.page-header -->

<div class="col-6 text-left text-white">
    <a class="btn btn-success" asp-controller="EmployeeLeaveTypes" asp-action="Create">Add Types</a>
</div>

<br />

<div class="row">
    <div class="col-xs-12">
        <table id="simple-table" class="table  table-bordered table-hover">
            <thead>
                <tr>
                    <th>Leave Name</th>
                    <th>Creation Date</th>
                    <th>Operations</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td> @item.Name</td>
                        <td>@item.DateCreated</td>
                        <td>
                            <div class="hidden-sm hidden-xs btn-group">

                                <a class="btn btn-xs btn-info" asp-controller="EmployeeLeaveTypes" asp-action="Edit" asp-route-id="@item.id">
                                    <i class="ace-icon fa fa-pencil bigger-120"></i>
                                </a>

                                <a class="btn btn-xs btn-danger" onclick="removeItem(@item.id)" data-id="@item.id">
                                    <i class="ace-icon fa fa-trash bigger-120"></i>
                                </a>

                                <button class="btn btn-xs btn-warning">
                                    <i class="ace-icon fa fa-flag bigger-120"></i>
                                </button>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div><!-- /.span -->
</div><!-- /.row -->


@section Scripts{
    <script type="text/javascript">
        //$(document).ready(function () {
        //});
            function removeItem(rowId) {
              swal({
                title: 'Are you sure that you want to delete?',
                text: 'Deleted data can not be recovered!',
                icon: 'warning',
                buttons: true,
                dangerMode: true
              }).then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: "DELETE",
                        url: "/EmployeeLeaveTypes/Delete/" + rowId,
                        success: function (data) {
                            if (data.success) {
                                toastr.success(data.message);
                                location.reload();
                            } else {
                                toastr.error(data.message);
                            }
                        }
                    });
                }
            });
        }
    </script>
}